### ISSUE TITLE
[Question] - How did u make popup browser install ? 

### ISSUE THREAD

**Issue by nejcdev** [eporsche/daybreak#10]
Where is this in code located? 

![image](https://user-images.githubusercontent.com/66303179/119774488-86d57100-bec2-11eb-997f-73879236b9ee.png)

**Comment by eporsche** [comment]
There is no specific place within the code. You need to fulfill the browser requirements for PWAs (progressive web apps).
This video should get you started: https://www.youtube.com/watch?v=KzvK809rl3Q

**Comment by nejcdev** [comment]
Thank you
