### ISSUE TITLE
[Suggestion] - disable mail sending on local env

### ISSUE THREAD

**Issue by Nejcc** [eporsche/daybreak#15]
if is mail not set on local env you get errors like this
```
Connection could not be established with host mailhog :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: No such host is known.
```

Solution:

```php
if (!app()->environment('local')) {
    Mail::to($absence->employee)->send(new AbsenceRemoved());
}
```

**Comment by Nejcc** [comment]
one example : app\Actions\AddAbsence.php:87

**Comment by nejcdev** [comment]
for the local or testing this is issue  yes or mabye you dont want to send any email at all and keep it without  mabye some config settings ? just an suggestion

**Comment by eporsche** [comment]
Just set the environment variable MAIL_MAILER to log and EMails won't be sent.
https://laravel.com/docs/8.x/mail#log-driver
