### ISSUE TITLE
[Issue] - Time locale  missin or is somewhere hidden 

### ISSUE THREAD

**Issue by nejcdev** [eporsche/daybreak#16]
## The time is different then the time on my PC    like few hours in between

![image](https://user-images.githubusercontent.com/66303179/119820738-19d9cf80-bef2-11eb-94c2-2d98ab21a3e0.png)

**Comment by foorschtbar** [comment]
Maybe the same problem like #8. Checkin and checkout uses UTC but i live in CEST and i cant adjust it.

**Comment by eporsche** [comment]
I commented in #8
