### ISSUE TITLE
[Suggestion] - Branching the git 

### ISSUE THREAD

**Issue by Nejcc** [eporsche/daybreak#20]
Strongly suggest  start branching the git workflow for your very nice project.

- Master (release / pre-release)  (lock master branch )
   - Stag (copy of production / pass all tests before marge to master )
   - Develop  (Main develop branch)
      -  Features/*
      -  Bugs/*
      -  Theme/*
      -  Security/*

:)

**Comment by eporsche** [comment]
Currently, it is not required to add more complexity to the git flow, since there is no "active" 5+ dev community working on the project. Moreover, at this stage, the project is in the pre-release phase.
