### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by ucorpintegration** [eporsche/daybreak#37]

**Comment by mediashock** [comment]
Its already there, edit your app config file and change `'locale' => 'de'`, to `'locale' => 'en'`

**Comment by noraj** [comment]
File to change for example for France:

- `.env`
  - `TZ=Europe/Paris`
- daybreak/config/app.php
  - `'locale' => 'fr',`
- daybreak/database/factories/LocationFactory.php
  - `'locale' => 'fr',`
  - `'time_zone' => 'Europe/Paris',`

https://github.com/eporsche/daybreak/blob/843aa17f3c6349215748ed7170512ff375fb12d1/config/app.php#L83

Could be changed to the following so people can change the lang from `.env`. See PR #41

So instead I just have to

- `.env`
  - `TZ=Europe/Paris`
  - `LANG=fr`
