### ISSUE TITLE
Adjust Timezone

### ISSUE THREAD

**Issue by foorschtbar** [eporsche/daybreak#8]
How could i adjust the timezone?

- Added `APP_TIMEZONE=Europe/Berlin` to `.env-file`
- Added Enviroment `TZ=Europe/Berlin`
- Added` Europe/Berlin` to` DB/locations/time_zone`

I also tried CEST as value, but the times are still in UTC.

**Comment by foorschtbar** [comment]
?

**Comment by eporsche** [comment]
Currently I am doing some refactoring on the timezone part.. you can have a look a the state here: [Commit](https://github.com/eporsche/daybreak/commit/8da7a470702d84779dd07b9ccd557d3b8afe63ce) 
Once implemented it should solve your issue. Dates will then always be saved in UTC with a custom timezone. The correct date will then be calulated, when it is read from the database. I am not sure when this will be finished though. Help would be appreciated.
